### PR TITLE
Auto generate a quantum link and sample documentation code from mc2 file

### PR DESCRIPTION
**Pull request by badele**
This Pull Request add a auto documentation feature. With some markers, you can add directly in your documentation a mc2 code file. You can also create a link to quantum backend server with mc2 code file.

### CODE REVIEW

**Comment by aurrelhebert** [comment]
Thanks for your PR! 
With an extracted configuration file for the back-end to reach and quantum URL, it could work offline as well (we design this hands-on to work during conferences with a local set-up). However, I still think that it's a little bit too much, when a direct link to each mc2 files would have been easier to do and to maintain ?

**Comment by PierreZ** [comment]
Thanks for the PR.

Like @aurrelhebert, it is feeling a bit too much for the need. I'm wondering if using Jekyll (or any other static generator) would be more interesting. I would love to have https://helloexoworld.github.io/hands-on :smile:. Can we generate Quantum links using standard out-of-the-box Jekyll ?

What do you think?

**Comment by badele** [comment]
If you like use jekyll, i think you can use a hook for generate include a mc2 file or generate an html link. The choice is in you side. But the idea is here :)

**Comment by PierreZ** [comment]
As we moved to Jekyll, this PS is irrelevant, closing it 😃

**Pull request closed without merging**
